server:
  # Port sẽ được định nghĩa trong docker-compose hoặc profile cụ thể
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  application:
    name: agri-trade-ls
  jpa:
    hibernate:
      ddl-auto: none # Để Flyway hoặc profile cụ thể quản lý (validate/update)
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false # Tắt mặc định, sẽ bật trong profile nếu cần
  mail:
    host: ${SPRING_MAIL_HOST:smtp.sendgrid.net}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:apikey}
    password: ${SPRING_MAIL_PASSWORD} # Sẽ lấy từ biến môi trường
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 3600000
      refresh-token:
        expiration-ms: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method

logging:
  level:
    root: INFO
    com.yourcompany.agritrade: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

google:
  auth:
    client-id: ${GOOGLE_CLIENT_ID}

firebase:
  storage:
    bucket-name: ${FIREBASE_STORAGE_BUCKET_NAME}
    service-account-key-path: ${FIREBASE_SERVICE_ACCOUNT_KEY_PATH:classpath:firebase-service-account-key.json}

payment:
  vnpay:
    version: "2.1.0"
    tmnCode: ${VNPAY_TMN_CODE}
    hashSecret: ${VNPAY_HASH_SECRET}
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    apiUrl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  momo:
    partnerCode: YOUR_MOMO_PARTNER_CODE
    accessKey: YOUR_MOMO_ACCESS_KEY
    secretKey: YOUR_MOMO_SECRET_KEY
    endpoint: https://test-payment.momo.vn/v2/gateway/api/create
    queryUrl: https://test-payment.momo.vn/v2/gateway/api/query
    refundUrl: ${MOMO_REFUND_URL:https://test-payment.momo.vn/v2/gateway/api/refund}

app:
  # Các giá trị cụ thể của app sẽ được định nghĩa trong từng profile
  mail:
    from: ${APP_MAIL_FROM:lanhquocvuong26@gmail.com}
    sender-name: "AgriTrade Platform"
  scheduler:
    invoice:
      cron: "0 0 1 * * ?"
      due_soon_days_before: 3
      overdue_admin_notify_after_days: 7
      payment_terms_days: 30